{% set name = "mfpymake" %}
{% set version = "1.2.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mfpymake-{{ version }}.tar.gz
  sha256: 752a675995f6ac99a31949828d820c195222c02e0c574668ed0d744cc1ee03f9

build:
  entry_points:
    - mfpymake = pymake.cmds.mfpymakecli:main
    - make-program = pymake.cmds.build:main
    - make-code-json = pymake.cmds.createjson:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=45
    - wheel
    - pip
  run:
    - python >=3.8
    - numpy
    - requests
    - networkx >=2.6.3
    - meson
    - ninja
    - pydotplus

test:
  imports:
    - pymake
  commands:
    - mfpymake --help
    - make-program --help
    - make-code-json --help

about:
  home: https://github.com/modflowpy/pymake
  summary: pymake is a Python package to compile MODFLOW-based models.
  license: CC0-1.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - jdhughes-usgs
    - wpbonelli
