{% set name = "mfpymake" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mfpymake-{{ version }}.tar.gz
  sha256: e2f81801a69a9699133aa096c07fb177d2320ca802dbd889ad714c9314f047e9

build:
  entry_points:
    - mfpymake = pymake.cmds.mfpymakecli:main
    - make-program = pymake.cmds.build:main
    - make-code-json = pymake.cmds.createjson:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=45
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - requests
    - networkx >=2.6.3
    - meson
    - ninja
    - pydotplus

test:
  requires:
    - python {{ python_min }}
  imports:
    - pymake
  commands:
    - mfpymake --help
    - make-program --help
    - make-code-json --help

about:
  home: https://github.com/modflowpy/pymake
  summary: pymake is a Python package to compile MODFLOW-based models.
  license: CC0-1.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - jdhughes-usgs
    - wpbonelli
